### ISSUE TITLE
Doesn't load in Android Chrome

### ISSUE THREAD

**Issue by quantizor** [tomocchino/isfiberreadyyet#2]
Testing using my Pixel. No idea why :/ I'll try and set up remote debugging tomorrow for clues

**Comment by ManasJayanth** [comment]
Think it's related to issue [#1231](https://github.com/facebookincubator/create-react-app/issues/1231) in `create-react-app` and seems to be fixed in [0.8.4](https://github.com/facebookincubator/create-react-app/releases/tag/v0.8.4)

**Comment by fairbairn** [comment]
ditto

**Comment by tomocchino** [comment]
I just deployed a new version with the latest CRA. I don't have an Android phone handy at the moment, but can you open this back up if that didn't fix it?
