### ISSUE TITLE
nondescript failing test shown

### ISSUE THREAD

**Issue by MMeent** [tomocchino/isfiberreadyyet#3]
As you can see [0] , there is one square for a nondescript test which would be in the ReactDomTextComponent-test, but I cannot find that nondescript test anywhere, so I think this is a bug on the parser side. The tests failing counter (n of N unit tests passing) does not seem to count this "test".

[0] : ![capture](https://cloud.githubusercontent.com/assets/2960313/26485939/40694628-41f9-11e7-8982-d62be9573487.PNG)

**Comment by tomocchino** [comment]
Thanks so much for finding / fixing this, @MMeent!
